### ISSUE TITLE
Bookmarks failing to save

### ISSUE THREAD

**Issue by marcellogalhardo** [joreilly/Confetti#307]
After bookmarking multiple talks, I noticed that many did not get save. I did not identify a pattern on why it is happening: it may be related with the quantity of bookmarks and/or a connection issue (with bad syncing, maybe?).

If the later, it would be great to receive a message if connection fails.

**Comment by martinbonnin** [comment]
Thanks for reporting this! Did they appeared as set but disappeared after a restart of the app? If you can find a way to reproduce, would be great. 

> If the later, it would be great to receive a message if connection fails.

Agreed. Any suggestion what to do in terms of UI? SnackBar, something else?

**Comment by martinbonnin** [comment]
> Did they appeared as set but disappeared after a restart of the app? If you can find a way to reproduce, would be great.

Never mind, I'm almost sure this is a backeng caching issue. I'll look into this.

> If the later, it would be great to receive a message if connection fails.

We should still do this though. Let me know if you have any idea

**Comment by marcellogalhardo** [comment]
> Did they appeared as set but disappeared after a restart of the app?

Yes, exactly. Sometimes just navigating to another screen and come back would make it disappear.

> If you can find a way to reproduce, would be great.
> Never mind, I'm almost sure this is a backeng caching issue. I'll look into this.

I suspect it to be a caching problem too.

> Any suggestion what to do in terms of UI? SnackBar, something else?

A SnackBar should be fine IMO.

Thank you for looking into it! 😀

**Comment by martinbonnin** [comment]
Thanks for the details! I'm pretty sure this was fixed with [this](https://github.com/joreilly/Confetti/pull/320/files#diff-7eda2724c5032aa940c89e62beab565ff5e04427e7e54765c5e823dca2620e62R30). Before that, the CDN would cache older benchmarks for 10min. This line disables caching for bookmarks. Let's wait a bit (not sure what version is on the Google play) to see if it's still happening

**Comment by joreilly** [comment]
I published version to production a few days ago but hasn't been approved yet.  @marcellogalhardo I can add you to internal testing channel if you want to DM me your google email address. (I believe fix should be in that but I'll publish version to that later as well just to be sure)

**Comment by martinbonnin** [comment]
Now that I think about it, the fix was server side so no need to even wait for Google here. @marcellogalhardo let us know if you see this bug again! Testing with latest internal channel would be interesting too nonetheless

**Comment by marcellogalhardo** [comment]
@martinbonnin the problem is still happening on current published version. @joreilly added me to the internal, and the problem doesn't seem to happen on the new version!

**Comment by marcellogalhardo** [comment]
I have tried further on the internal version, and it seems it keep happening.

I have recorded a video showing the problem: (Confetti-Bookmark-Issues.mp4)[https://drive.google.com/file/d/143cTuqe_FEeM13xmjH91d4sRYim85esq/view?usp=drivesdk]

**Comment by martinbonnin** [comment]
Many thanks for the video 🙏 . Gave it a quick try here and couldn't reproduce unfortunately :(. I'll add error messages when the call fails, hopefully that'll give us more info.

**Comment by martinbonnin** [comment]
Should be good with better backend-side cache control
